# Generated by Django 6.0.3 on 2026-04-02 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonthResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('planned_result', models.DecimalField(decimal_places=1, max_digits=12)),
                ('actual_result', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='YearObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(default='Your Brand', max_length=100)),
                ('team', models.CharField(default='Your Department', max_length=200)),
                ('year', models.IntegerField()),
                ('goal', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('planned_result', models.DecimalField(decimal_places=1, max_digits=12)),
                ('actual_result', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Komentarai / Problemos sprendimas')),
                ('month_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.monthresult')),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='okr.unit')),
            ],
        ),
        migrations.CreateModel(
            name='YearKeyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('annual_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='okr.unit')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.yearobjective')),
            ],
        ),
        migrations.AddField(
            model_name='monthresult',
            name='monthly_key_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okr.yearkeyresult'),
        ),
    ]
